// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYf17BTAP9VDnRxkTQqHDhQoD4rygvzck',
    appId: '1:115095298627:android:7666971b71f7b6fc1aeaf6',
    messagingSenderId: '115095298627',
    projectId: 'databaza84',
    databaseURL: 'https://databaza84-default-rtdb.firebaseio.com',
    storageBucket: 'databaza84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO27EFMTge3rs_vWwz7L2yDv-tV837dbQ',
    appId: '1:115095298627:ios:75bf9f878499deb21aeaf6',
    messagingSenderId: '115095298627',
    projectId: 'databaza84',
    databaseURL: 'https://databaza84-default-rtdb.firebaseio.com',
    storageBucket: 'databaza84.appspot.com',
    iosClientId: '115095298627-8678ln5tki44ktjqehs77kipdojptvj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
